### ISSUE TITLE
手動で開いた日にちを自動で出力すようにする

### ISSUE THREAD

**Issue by TirolJPN** [TirolJPN/desired-schedule-generator#2]
## ToDo
そもそも行ける日だけ入力すれば良いのではということに気がついた

- [x] ~~希望日程の期間を選択できる(Home.vue)~~
- [x] ~~選択した希望期間の中から、除外する日にちを0個以上選択できるフォーム(ExcludedDate.vue)を生成できる~~
- [x] ~~Home.vueからExcludedDate.vueに希望日程の期間の情報を表すオブジェクトを渡すことができる~~
- [ ] ~~Home.vue側で除外する時間の範囲が被らないようなバリデーシンをHome.vueにかける~~
- [ ] ~~Home.vueのdataと任意の個数のExcludedDate.vueのdataから、希望する日程の情報を自動生成できる~~

**Comment by TirolJPN** [comment]
enabledDatesの各要素(各日にち)で時間の演算を、enabledDatesとexcludedDatesの二重ループで行う。

**Comment by TirolJPN** [comment]
excludedDatesによる都合のつく時間(有効時間と呼ぶ)の穴あけのパターンは次の通り

1. excludedDates.startTimeとexcludeDates.endingTimeの範囲が有効時間に含まれる
2. excludeDates.startTImeのみ有効時間に含まれる
3. excludeDates.endingTimeのみ有効時間に含まれる
4. excludeDates.startTimeもexcludeDates.endingTimeのどちらとも有効時間に含まれない

 
2.
